export const CustomerService = {
  getData() {
    return [
      {
        id: 1000,
        name: "James Butt",
        address: "Benton, John B Jr",
        phone_number: "+1 (926) 492-3643",
        date: "2015-09-13",
        verified: true,
        activity: 17,
        email: "john@dow.com",
      },
      {
        id: 1001,
        name: "Josephine Darakjy",
        address: "Chanay, Jeffrey A Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2019-02-09",
        verified: true,
        activity: 0,
        email: "john@dow.com",
      },
      {
        id: 1002,
        name: "Art Venere",
        address: "Chemel, James L Cpa",
        phone_number: "+1 (926) 492-3643",
        date: "2017-05-13",
        verified: false,
        activity: 63,
        email: "john@dow.com",
      },
      {
        id: 1003,
        name: "Lenna Paprocki",
        address: "Feltz Printing Service",
        phone_number: "+1 (926) 492-3643",
        date: "2020-09-15",
        verified: false,
        activity: 37,
        email: "john@dow.com",
      },
      {
        id: 1004,
        name: "Donette Foller",
        address: "Printing Dimensions",
        phone_number: "+1 (926) 492-3643",
        date: "2016-05-20",
        verified: true,
        activity: 33,
        email: "john@dow.com",
      },
      {
        id: 1005,
        name: "Simona Morasca",
        address: "Chapman, Ross E Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2018-02-16",
        verified: false,
        activity: 68,
        email: "john@dow.com",
      },
      {
        id: 1006,
        name: "Mitsue Tollner",
        address: "Morlong Associates",
        phone_number: "+1 (926) 492-3643",
        date: "2018-02-19",
        verified: true,
        activity: 54,
        email: "john@dow.com",
      },
      {
        id: 1007,
        name: "Leota Dilliard",
        address: "Commercial Press",
        phone_number: "+1 (926) 492-3643",
        date: "2019-08-13",
        verified: true,
        activity: 69,
        email: "john@dow.com",
      },
      {
        id: 1008,
        name: "Sage Wieser",
        address: "Truhlar And Truhlar Attys",
        phone_number: "+1 (926) 492-3643",
        date: "2018-11-21",
        verified: true,
        activity: 76,
        email: "john@dow.com",
      },
      {
        id: 1009,
        name: "Kris Marrier",
        address: "King, Christopher A Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2015-07-07",
        verified: false,
        activity: 3,
        email: "john@dow.com",
      },
      {
        id: 1010,
        name: "Minna Amigon",
        address: "Dorl, James J Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2018-11-07",
        verified: false,
        activity: 38,
        email: "john@dow.com",
      },
      {
        id: 1011,
        name: "Abel Maclead",
        address: "Rangoni Of Florence",
        phone_number: "+1 (926) 492-3643",
        date: "2017-03-11",
        verified: true,
        activity: 87,
        email: "john@dow.com",
      },
      {
        id: 1012,
        name: "Kiley Caldarera",
        address: "Feiner Bros",
        phone_number: "+1 (926) 492-3643",
        date: "2015-10-20",
        verified: false,
        activity: 80,
        email: "john@dow.com",
      },
      {
        id: 1013,
        name: "Graciela Ruta",
        address: "Buckley Miller & Wright",
        phone_number: "+1 (926) 492-3643",
        date: "2016-07-25",
        verified: false,
        activity: 59,
        email: "john@dow.com",
      },
      {
        id: 1014,
        name: "Cammy Albares",
        address: "Rousseaux, Michael Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2019-06-25",
        verified: true,
        activity: 90,
        email: "john@dow.com",
      },
      {
        id: 1015,
        name: "Mattie Poquette",
        address: "Century Communications",
        phone_number: "+1 (926) 492-3643",
        date: "2017-12-12",
        verified: false,
        activity: 52,
        email: "john@dow.com",
      },
      {
        id: 1016,
        name: "Meaghan Garufi",
        address: "Bolton, Wilbur Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2018-07-04",
        verified: false,
        activity: 31,
        email: "john@dow.com",
      },
      {
        id: 1017,
        name: "Gladys Rim",
        address: "T M Byxbee address Pc",
        phone_number: "+1 (926) 492-3643",
        date: "2020-02-27",
        verified: true,
        activity: 48,
        email: "john@dow.com",
      },
      {
        id: 1018,
        name: "Yuki Whobrey",
        address: "Farmers Insurance Group",
        phone_number: "+1 (926) 492-3643",
        date: "2017-12-21",
        verified: true,
        activity: 16,
        email: "john@dow.com",
      },
      {
        id: 1019,
        name: "Fletcher Flosi",
        address: "Post Box Services Plus",
        phone_number: "+1 (926) 492-3643",
        date: "2016-01-04",
        verified: true,
        activity: 19,
        email: "john@dow.com",
      },
      {
        id: 1020,
        name: "Bette Nicka",
        address: "Sport En Art",
        phone_number: "+1 (926) 492-3643",
        date: "2016-10-21",
        verified: false,
        activity: 100,
        email: "john@dow.com",
      },
      {
        id: 1021,
        name: "Veronika Inouye",
        address: "C 4 Network Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2017-03-24",
        verified: false,
        activity: 72,
        email: "john@dow.com",
      },
      {
        id: 1022,
        name: "Willard Kolmetz",
        address: "Ingalls, Donald R Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2017-04-15",
        verified: true,
        activity: 94,
        email: "john@dow.com",
      },
      {
        id: 1023,
        name: "Maryann Royster",
        address: "Franklin, Peter L Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2017-03-11",
        verified: false,
        activity: 56,
        email: "john@dow.com",
      },
      {
        id: 1024,
        name: "Alisha Slusarski",
        address: "Wtlz Power 107 Fm",
        phone_number: "+1 (926) 492-3643",
        date: "2018-03-27",
        verified: true,
        activity: 7,
        email: "john@dow.com",
      },
      {
        id: 1025,
        name: "Allene Iturbide",
        address: "Ledecky, David Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2016-02-20",
        verified: true,
        activity: 1,
        email: "john@dow.com",
      },
      {
        id: 1026,
        name: "Chanel Caudy",
        address: "Professional Image Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2018-06-24",
        verified: true,
        activity: 26,
        email: "john@dow.com",
      },
      {
        id: 1027,
        name: "Ezekiel Chui",
        address: "Sider, Donald C Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2016-09-24",
        verified: false,
        activity: 76,
        email: "john@dow.com",
      },
      {
        id: 1028,
        name: "Willow Kusko",
        address: "U Pull It",
        phone_number: "+1 (926) 492-3643",
        date: "2020-04-11",
        verified: true,
        activity: 7,
        email: "john@dow.com",
      },
      {
        id: 1029,
        name: "Bernardo Figeroa",
        address: "Clark, Richard Cpa",
        phone_number: "+1 (926) 492-3643",
        date: "2018-04-11",
        verified: true,
        activity: 81,
        email: "john@dow.com",
      },
      {
        id: 1030,
        name: "Ammie Corrio",
        address: "Moskowitz, Barry S",
        phone_number: "+1 (926) 492-3643",
        date: "2016-06-11",
        verified: true,
        activity: 56,
        email: "john@dow.com",
      },
      {
        id: 1031,
        name: "Francine Vocelka",
        address: "Cascade Realty Advisors Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2017-08-02",
        verified: true,
        activity: 94,
        email: "john@dow.com",
      },
      {
        id: 1032,
        name: "Ernie Stenseth",
        address: "Knwz Newsradio",
        phone_number: "+1 (926) 492-3643",
        date: "2018-06-06",
        verified: true,
        activity: 68,
        email: "john@dow.com",
      },
      {
        id: 1033,
        name: "Albina Glick",
        address: "Giampetro, Anthony D",
        phone_number: "+1 (926) 492-3643",
        date: "2019-08-08",
        verified: true,
        activity: 85,
        email: "john@dow.com",
      },
      {
        id: 1034,
        name: "Alishia Sergi",
        address: "Milford Enterprises Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2018-05-19",
        verified: false,
        activity: 46,
        email: "john@dow.com",
      },
      {
        id: 1035,
        name: "Solange Shinko",
        address: "Mosocco, Ronald A",
        phone_number: "+1 (926) 492-3643",
        date: "2015-02-12",
        verified: true,
        activity: 32,
        email: "john@dow.com",
      },
      {
        id: 1036,
        name: "Jose Stockham",
        address: "Tri State Refueler Co",
        phone_number: "+1 (926) 492-3643",
        date: "2018-04-25",
        verified: true,
        activity: 77,
        email: "john@dow.com",
      },
      {
        id: 1037,
        name: "Rozella Ostrosky",
        address: "Parkway address",
        phone_number: "+1 (926) 492-3643",
        date: "2016-02-27",
        verified: true,
        activity: 66,
        email: "john@dow.com",
      },
      {
        id: 1038,
        name: "Valentine Gillian",
        address: "Fbs Business Finance",
        phone_number: "+1 (926) 492-3643",
        date: "2019-09-17",
        verified: true,
        activity: 25,
        email: "john@dow.com",
      },
      {
        id: 1039,
        name: "Kati Rulapaugh",
        address: "Eder Assocs Consltng Engrs Pc",
        phone_number: "+1 (926) 492-3643",
        date: "2016-12-03",
        verified: false,
        activity: 51,
        email: "john@dow.com",
      },
      {
        id: 1040,
        name: "Youlanda Schemmer",
        address: "Tri M Tool Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2017-12-15",
        verified: true,
        activity: 49,
        email: "john@dow.com",
      },
      {
        id: 1041,
        name: "Dyan Oldroyd",
        address: "International Eyelets Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2017-02-02",
        verified: false,
        activity: 5,
        email: "john@dow.com",
      },
      {
        id: 1042,
        name: "Roxane Campain",
        address: "Rapid Trading Intl",
        phone_number: "+1 (926) 492-3643",
        date: "2018-12-25",
        verified: false,
        activity: 100,
        email: "john@dow.com",
      },
      {
        id: 1043,
        name: "Lavera Perin",
        address: "Abc Enterprises Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2018-04-10",
        verified: false,
        activity: 71,
        email: "john@dow.com",
      },
      {
        id: 1044,
        name: "Erick Ferencz",
        address: "Cindy Turner Associates",
        phone_number: "+1 (926) 492-3643",
        date: "2018-05-06",
        verified: true,
        activity: 54,
        email: "john@dow.com",
      },
      {
        id: 1045,
        name: "Fatima Saylors",
        address: "Stanton, James D Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2019-07-10",
        verified: true,
        activity: 93,
        email: "john@dow.com",
      },
      {
        id: 1046,
        name: "Jina Briddick",
        address: "Grace Pastries Inc",
        phone_number: "+1 (926) 492-3643",
        date: "2018-02-19",
        verified: false,
        activity: 97,
        email: "john@dow.com",
      },
      {
        id: 1047,
        name: "Kanisha Waycott",
        address: "Schroer, Gene E Esq",
        phone_number: "+1 (926) 492-3643",
        date: "2019-11-27",
        verified: false,
        activity: 80,
        email: "john@dow.com",
      },
      {
        id: 1048,
        name: "Emerson Bowley",
        address: "Knights Inn",
        phone_number: "+1 (926) 492-3643",
        date: "2018-11-24",
        verified: false,
        activity: 63,
        email: "john@dow.com",
      },
      {
        id: 1049,
        name: "Blair Malet",
        address: "Bollinger Mach Shp & Shipyard",
        phone_number: "+1 (926) 492-3643",
        date: "2018-04-19",
        verified: true,
        activity: 92,
        email: "john@dow.com",
      },
      {
        id: 1050,
        name: "Brock Bolognia",
        address: "Orinda News",
        date: "2019-09-06",
        verified: true,
        activity: 72,
        email: "john@dow.com",
      },
    ];
  },

  getCustomersSmall() {
    return Promise.resolve(this.getData().slice(0, 10));
  },

  getCustomersMedium() {
    return Promise.resolve(this.getData().slice(0, 50));
  },

  getCustomersLarge() {
    return Promise.resolve(this.getData().slice(0, 200));
  },

  getCustomersXLarge() {
    return Promise.resolve(this.getData());
  },

  getCustomers(params) {
    const queryParams = params
      ? Object.keys(params)
          .map(
            (k) => encodeURIComponent(k) + "=" + encodeURIComponent(params[k])
          )
          .join("&")
      : "";

    return fetch(
      "https://www.primefaces.org/data/customers?" + queryParams
    ).then((res) => res.json());
  },
};
