export const TechniciansList = {
  getData() {
    return [
      {
        id: 1000,
        name: "James Butt",
        company: "Benton, John B Jr",
        phone_number: "+1 (866) 430-2829",
        date: "2015-09-13",
        status: true,
        activity: 17,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "lenajustice@austech.com",
        balance: 70663,
        position: "Cleaning Tech",
      },
      {
        id: 1001,
        name: "Josephine Darakjy",
        company: "Chanay, Jeffrey A Esq",
        phone_number: "+1 (805) 408-2618",
        date: "2019-02-09",
        status: true,
        activity: 0,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "raemonroe@austech.com",
        balance: 82429,
        position: "Cleaning Tech",
      },
      {
        id: 1002,
        name: "Art Venere",
        company: "Chemel, James L Cpa",
        phone_number: "+1 (936) 442-2218",
        date: "2017-05-13",
        status: false,
        activity: 63,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "valeriakoch@austech.com",
        balance: 28334,
        position: "Cleaning Tech",
      },
      {
        id: 1003,
        name: "Lenna Paprocki",
        company: "Feltz Printing Service",
        phone_number: "+1 (862) 541-3571",
        date: "2020-09-15",
        status: false,
        activity: 37,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "wellsherrera@austech.com",
        balance: 88521,
        position: "Cleaning Tech",
      },
      {
        id: 1004,
        name: "Donette Foller",
        company: "Printing Dimensions",
        phone_number: "+1 (886) 476-2282",
        date: "2016-05-20",
        status: true,
        activity: 33,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "salazarsavage@austech.com",
        balance: 93905,
        position: "Cleaning Tech",
      },
      {
        id: 1005,
        name: "Simona Morasca",
        company: "Chapman, Ross E Esq",
        phone_number: "+1 (867) 445-2455",
        date: "2018-02-16",
        status: false,
        activity: 68,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "ivymercer@austech.com",
        balance: 50041,
        position: "Cleaning Tech",
      },
      {
        id: 1006,
        name: "Mitsue Tollner",
        company: "Morlong Associates",
        phone_number: "+1 (927) 455-3640",
        date: "2018-02-19",
        status: true,
        activity: 54,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "clarewagner@austech.com",
        balance: 58706,
        position: "Cleaning Tech",
      },
      {
        id: 1007,
        name: "Leota Dilliard",
        company: "Commercial Press",
        phone_number: "+1 (897) 441-2570",
        date: "2019-08-13",
        status: true,
        activity: 69,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "kaylafaulkner@austech.com",
        balance: 26640,
        position: "Cleaning Tech",
      },
      {
        id: 1008,
        name: "Sage Wieser",
        company: "Truhlar And Truhlar Attys",
        phone_number: "+1 (897) 441-2570",
        date: "2018-11-21",
        status: true,
        activity: 76,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "meyerpierce@austech.com",
        balance: 65369,
        position: "Cleaning Tech",
      },
      {
        id: 1009,
        name: "Kris Marrier",
        company: "King, Christopher A Esq",
        phone_number: "+1 (897) 441-2570",
        date: "2015-07-07",
        status: false,
        activity: 3,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "jessiestein@austech.com",
        balance: 63451,
        position: "Cleaning Tech",
      },
      {
        id: 1010,
        name: "Minna Amigon",
        company: "Dorl, James J Esq",
        phone_number: "+1 (897) 441-2570",
        date: "2018-11-07",
        status: false,
        activity: 38,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "esteskemp@austech.com",
        balance: 71169,
        position: "Cleaning Tech",
      },
      {
        id: 1011,
        name: "Abel Maclead",
        company: "Rangoni Of Florence",
        phone_number: "+1 (897) 441-2570",
        date: "2017-03-11",
        status: true,
        activity: 87,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "tamikaholloway@austech.com",
        balance: 96842,
        position: "Cleaning Tech",
      },
      {
        id: 1012,
        name: "Kiley Caldarera",
        company: "Feiner Bros",
        phone_number: "+1 (897) 441-2570",
        date: "2015-10-20",
        status: false,
        activity: 80,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "lenoreglover@austech.com",
        balance: 92734,
        position: "Cleaning Tech",
      },
      {
        id: 1013,
        name: "Graciela Ruta",
        company: "Buckley Miller & Wright",
        phone_number: "+1 (897) 441-2570",
        date: "2016-07-25",
        status: false,
        activity: 59,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "velasquezhatfield@austech.com",
        balance: 45250,
        position: "Cleaning Tech",
      },
      {
        id: 1014,
        name: "Cammy Albares",
        company: "Rousseaux, Michael Esq",
        phone_number: "+1 (897) 441-2570",
        date: "2019-06-25",
        status: true,
        activity: 90,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "farmergilmore@austech.com",
        balance: 30236,
        position: "Cleaning Tech",
      },
      {
        id: 1015,
        name: "Mattie Poquette",
        company: "Century Communications",
        phone_number: "+1 (897) 441-2570",
        date: "2017-12-12",
        status: false,
        activity: 52,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "alishaowens@austech.com",
        balance: 64533,
        position: "Cleaning Tech",
      },
      {
        id: 1016,
        name: "Meaghan Garufi",
        company: "Bolton, Wilbur Esq",
        phone_number: "+1 (897) 441-2570",
        date: "2018-07-04",
        status: false,
        activity: 31,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "valentinedonaldson@austech.com",
        balance: 37279,
        position: "Cleaning Tech",
      },
      {
        id: 1017,
        name: "Gladys Rim",
        company: "T M Byxbee Company Pc",
        phone_number: "+1 (897) 441-2570",
        date: "2020-02-27",
        status: true,
        activity: 48,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "martineztorres@austech.com",
        balance: 27381,
        position: "Cleaning Tech",
      },
      {
        id: 1018,
        name: "Yuki Whobrey",
        company: "Farmers Insurance Group",
        phone_number: "+1 (897) 441-2570",
        date: "2017-12-21",
        status: true,
        activity: 16,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "wilmabentley@austech.com",
        balance: 9257,
        position: "Cleaning Tech",
      },
      {
        id: 1019,
        name: "Fletcher Flosi",
        company: "Post Box Services Plus",
        phone_number: "+1 (897) 441-2570",
        date: "2016-01-04",
        status: true,
        activity: 19,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "mcleankeller@austech.com",
        balance: 67783,
        position: "Cleaning Tech",
      },
      {
        id: 1020,
        name: "Bette Nicka",
        company: "Sport En Art",
        phone_number: "+1 (897) 441-2570",
        date: "2016-10-21",
        status: false,
        activity: 100,
        appreciation: {
          like: 45,
          dislike: 3,
        },
        email: "lynnemcneil@austech.com",
        balance: 4609,
        position: "Cleaning Tech",
      },
    ];
  },

  getTechniciansSmall() {
    return Promise.resolve(this.getData().slice(0, 10));
  },

  getTechniciansMedium() {
    return Promise.resolve(this.getData().slice(0, 50));
  },

  getTechniciansLarge() {
    return Promise.resolve(this.getData().slice(0, 200));
  },

  getTechniciansXLarge() {
    return Promise.resolve(this.getData());
  },

  getTechnicians(params) {
    const queryParams = params
      ? Object.keys(params)
          .map(
            (k) => encodeURIComponent(k) + "=" + encodeURIComponent(params[k])
          )
          .join("&")
      : "";

    return fetch(
      "https://www.primefaces.org/data/customers?" + queryParams
    ).then((res) => res.json());
  },
};
